### ISSUE TITLE
http client总是打印日志进入loghub

### ISSUE THREAD

**Issue by SpinSi** [aliyun/aliyun-log-log4j-appender#3]
**Q: 把日志级别设置成 DEBUG 之后，aliyun-log-log4j-appender 依赖的第三方库 apache httpclient 会输出大量的日志，如何把这部分日志关闭？

A: 可以在您的 log4j.properties 文件中添加如下内容

log4j.logger.org.apache.http=OFF
log4j.logger.org.apache.http.wire=OFF
log4j.logger.com.aliyun=OFF**

按照您写的方法设置并没有作用

**Comment by brucewu-fly** [comment]
@Moving521  参考文档常见问题第一条
https://github.com/aliyun/aliyun-log-log4j-appender/blob/master/README_CN.md#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by brucewu-fly** [comment]
@Moving521 请问你输出了什么内容？

**Comment by brucewu-fly** [comment]
Q: 在 log4j.properties 中设置了 com.aliyun.openservices.log.producer.inner=OFF 为何还能看到 com.aliyun.openservices.log.producer.inner.IOThread 输出的日志？

A：该线程是在 log4j 完成初始化之前启动的，输出日志的那个时刻 log4j 框架还未完成 logging level 的设置。一旦 log4j 完成 logging level 的设置，IOThread 便不会输出日志。
